#!/usr/bin/env bash
# Cut a sharedwatch release.
#
# Does:
#   1. Verifies the working tree is clean and on a tagged commit (or --allow-dirty).
#   2. Runs gitleaks scan over the tree (defense in depth).
#   3. Runs gofmt -l, go vet, go test in src/.
#   4. Cross-compiles binaries for {linux,darwin} x {amd64,arm64}.
#   5. Packages each as sharedwatch_<version>_<platform>.tar.gz under dist/.
#   6. Writes dist/manifest.yaml with SHA-256 of each tarball + sizes.
#   7. Prints next-step instructions (git tag + push + gh release create).
#
# Does NOT:
#   - tag the commit (you do that)
#   - push to git or upload to GitHub (you do that)
#   - run sudo or write outside the repo
#
# Usage:
#   ./scripts/release.sh --version v0.8.0
#   ./scripts/release.sh --version v0.8.0 --allow-dirty   # skip clean-tree check

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$HERE")"
SRC="$REPO_ROOT/src"
DIST="$REPO_ROOT/dist"

VERSION=""
ALLOW_DIRTY=0
SKIP_GITLEAKS=0

while [ $# -gt 0 ]; do
  case "$1" in
    --version)       VERSION="$2"; shift 2 ;;
    --allow-dirty)   ALLOW_DIRTY=1; shift ;;
    --skip-gitleaks) SKIP_GITLEAKS=1; shift ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

[ -n "$VERSION" ] || { echo "ERROR: --version vX.Y.Z required" >&2; exit 2; }
case "$VERSION" in v[0-9]*) ;; *) echo "ERROR: version must start with v (got $VERSION)" >&2; exit 2 ;; esac

log() { printf '[release] %s\n' "$*"; }
die() { printf '[release] ERROR: %s\n' "$*" >&2; exit 1; }

cd "$REPO_ROOT"

# 1. Clean tree
if [ "$ALLOW_DIRTY" = "0" ]; then
  if [ -n "$(git status --porcelain)" ]; then
    die "working tree dirty; commit/stash or pass --allow-dirty"
  fi
fi

# 2. gitleaks
if [ "$SKIP_GITLEAKS" = "0" ]; then
  if command -v gitleaks >/dev/null 2>&1; then
    log "gitleaks scan"
    gitleaks dir --no-banner --redact --exit-code 1 . || die "gitleaks found secrets"
  else
    log "gitleaks not found in PATH; skipping (install via .githooks/install.sh or pass --skip-gitleaks)"
  fi
fi

# 3. Fmt / vet / test
cd "$SRC"
log "gofmt check"
unformatted="$(gofmt -l .)"
[ -z "$unformatted" ] || die "gofmt -l found unformatted files:\n$unformatted"

log "go vet"
go vet ./...

log "go test"
go test ./... -count=1

# 4. Cross-compile
rm -rf "$DIST"
mkdir -p "$DIST"

platforms=(
  "linux amd64"
  "linux arm64"
  "darwin amd64"
  "darwin arm64"
)

declare -a tarballs=()

for p in "${platforms[@]}"; do
  goos="${p%% *}"
  goarch="${p##* }"
  out="sharedwatch"
  staging="$DIST/staging_${goos}_${goarch}"
  mkdir -p "$staging"

  log "build $goos/$goarch"
  GOOS="$goos" GOARCH="$goarch" CGO_ENABLED=0 \
    go build -trimpath -ldflags "-s -w -X main.Version=$VERSION" \
    -o "$staging/$out" ./cmd/sharedwatch

  # Bundle binary + LICENSE + README for the tarball
  cp "$REPO_ROOT/LICENSE" "$staging/LICENSE"
  cp "$SRC/README.md" "$staging/README.md" 2>/dev/null || true

  tarball="sharedwatch_${VERSION#v}_${goos}_${goarch}.tar.gz"
  ( cd "$staging" && tar -czf "$DIST/$tarball" . )
  rm -rf "$staging"
  tarballs+=("$tarball")
  log "  -> dist/$tarball"
done

# 5. Manifest
log "writing dist/manifest.yaml"
{
  echo "# sharedwatch release manifest"
  echo "# Generated by scripts/release.sh"
  echo "name: sharedwatch"
  echo "version: $VERSION"
  echo "license: MIT"
  echo "released_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "source: \"https://github.com/${SHAREDWATCH_REPO:-ab0t-com/sharedwatch}\""
  echo "artifacts:"
  for t in "${tarballs[@]}"; do
    sz=$(stat -c %s "$DIST/$t" 2>/dev/null || stat -f %z "$DIST/$t")
    if command -v sha256sum >/dev/null 2>&1; then
      sha=$(sha256sum "$DIST/$t" | awk '{print $1}')
    else
      sha=$(shasum -a 256 "$DIST/$t" | awk '{print $1}')
    fi
    echo "  - file: $t"
    echo "    sha256: $sha"
    echo "    size_bytes: $sz"
  done
} > "$DIST/manifest.yaml"

log "release artifacts ready in dist/"
ls -la "$DIST"

cat <<EOF

Next steps (you, not this script):
  git tag -a $VERSION -m "release $VERSION"
  git push origin $VERSION
  gh release create $VERSION dist/*.tar.gz dist/manifest.yaml \\
    --title "$VERSION" --notes-file src/CHANGELOG.md
EOF
